name = "Brain Stem"
license = "MIT"
licenselink = "https://github.com/daylinmorgan/brain-stem/blob/main/LICENSE"
description = "hugo theme for your second brain (zettlekasten)"

[author]
  name = "Daylin Morgan"
  homepage = "https://dayl.in"
